config/routes.rb
Simnect::Application.routes.draw do
  get "sessions/create"
  get "pages/index"
  get "pages/intro"
  get "pages/about"
  get "pages/team"
  get "pages/contact"

   root 'pages#index'

  get 'signin' => 'pages#signin', as: :signin
  match  "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]
  match '/auth/:provider/callback' => 'sessions#create' , via: [:get, :post]
  

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
      find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
    end

    def self.create_with_omniauth(auth)
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["info"]["name"]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  

  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @title = 'Simnect'
  end

  def intro
  end

  def about
  end

  def team
  end

  def contact
  end

  def signin
    @title = 'Sign In'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"    
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navbar -->
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
    		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
          	</a>
          	<a class="brand scroller" data-section="html" href='pages/index'> Simnect</a>
		  	<div class="nav-collapse collapse">
                <ul class="nav pull-right">
                  	 <!-- <li><a href="#" class="toggle_video">Toggle Video Demo</a></li>-->
										 <% if current_user %>
										 Welcome, <%= current_user.name %>!
										 <%= link_to "Sign Out", signout_path %>
										 <% else %>
                     <li><%= link_to "Sign in", signin_path %></li><% end %>
                    <li><a href="index#about" class="scroller" data-section="#about">About</a></li>
                    <li><a href="team" class="scroller" data-section="#team">The Team</a></li>
                    <li><a href="index#contact" class="scroller" data-section="#contact">I'm Biz</a></li>
                </ul>
	        </div>
        </div>
      </div>
    </div>
    <!-- end Navbar -->
    	
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/_create.html.erb
<p>
  <strong>Don&rsquo;t use these services?</strong>
	<%= link_to "Create an account", "/auth/identity/register" %> 
</p>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
 <!-- #intro -->
	<div class="main-container">
		<div class="container-fluid" id="intro">	
		<div class="container">	
			<div class="row span6 center">
				<h1>Change the way the mobile advertises.</h1>
				<p>Increase the value of app users' daily consumption by helping them gain free virtual items in their favorite apps; encourage developers sell more in-app virtual items and enhance user experience; help local business interact with customers better, generate more sales and invest Ads expense more effectively.

	</p>
		 <% if !current_user %>				
				<a href="/auth/identity/register" class="btn btn-xlarge btn-purple">Sign Up</a>
			<% end %>
			</div>	
		</div>
	</div>
    <!-- ends Intro --> 
 <!-- #about -->
<div class="container-fluid" id="about">
		<div class="container light">
			<h1>What can we offer</h1>
		<ul class="thumbnails">
		  <li class="span4">
		    <div class="thumbnail">
		      <img alt="" src="assets/img/icon1.png">
		      <h3>Cross-Platform</h3>
		      <p>Simnect a platform for both mobile app developers and local business to find optimal cooperation.</p>
		    </div>
		  </li>
		
		  <li class="span4">
		    <div class="thumbnail">
		      <img alt="" src="assets/img/icon2.png">
		      <h3>Items Earning</h3>
		      <p>Simnect is planned to start as an app for users to gain free virtual items in only three steps.</p>
		    </div>
		  </li>
		  
		  <li class="span4">
		    <div class="thumbnail">
		       <img alt="" src="assets/img/icon3.png">
		      <h3>Data Mining</h3>
		      <p>Simnect is a platform to provide big data and cloud computing service for developers and business and help them manage their Ads behavior more effectively and accurately.</p>
		    </div>
		  </li>
		</ul>
	</div>
</div>
     <!-- ends About -->
	
      <!-- #contact -->   	
	<div class="container-fluid" id="contact">
	<div class="container dark">
		<h1>Get in contact with us</h1>	
	
		<div class="span5">			
			<form>
				  <div class="control-group">
				    <label class="control-label" for="inputName">Biz Name</label>
				    <div class="controls">
				      <input type="text" class="span4" id="inputName" placeholder="Name">
				    </div>
				  </div>
				  <div class="control-group">
				    <label class="control-label" for="inputEmail">Email</label>
				    <div class="controls">
				      <input type="text" class="span4" id="inputEmail" placeholder="Email">
				    </div>
				  </div>
				  <div class="control-group">
				    <label class="control-label" for="inputContact">Message</label>
				    <div class="controls">
				     <textarea id="inputContact" class="span4"></textarea>
				    </div>
				  </div>
				  <div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn btn-purple">Contact Us</button>
				    </div>
				  </div>
			</form>
		</div>
	
		<div class="span4">	
				<h2>Pop in for a chat</h2>
				
				<p>Behind the app, there is a platform for local business and app developers to search for optimal cooperation, like shopping at Amazon, manage the integrated promotions and analyze the data for future choices of partners and promotion products.</p>
	
				<address>
				  <strong>Simnect LLC.</strong><br>
				  Address<br>
				  City,State<br>
				  <abbr title="Phone">P:</abbr> (302) 766-3125
				</address>
				 
				<address>
				  <strong>Full Name</strong><br>
				  <a href="mailto:#">interbubu@gmail.com</a>
				</address>		
		</div>		
	</div>
</div>   <!-- End Contact -->  
	</div>
<script>
$(function () {
    $(window).scroll(function(){
    // global scroll to top button
        if ($(this).scrollTop() > 300) {
            $('.scrolltop').fadeIn();
        } else {
            $('.scrolltop').fadeOut();
        }        
    });
    
    // scroll nav
    $('.scroller').click(function(){
    	var section = $($(this).data("section"));
    	var top = section.offset().top-82;
        $("html, body").animate({ scrollTop: top }, 700);
        return false;
    });

	    	    
    // For the purpose of the demo this allows you to toggle the background between video and img
    $('.toggle_video').click(function(){
	    
	   $('#big-video-wrap').fadeToggle();
	   return false; 
	    
    });
    
	// BigVideo Setup
    var BV = new $.BigVideo({useFlashForFirefox:false});
	BV.init();
    if (Modernizr.touch) {
    	// fallback image for mobile devices
        BV.show('assets/img/bg2.jpg');
    } else {
        BV.show('assets/video/frontier.mp4',
        {ambient:true, doLoop:true, altSource:'assets/video/frontier.ogv'});
    }   
    
            
});

app/views/pages/intro.html.erb
<h1>Pages#intro</h1>
<p>Find me in app/views/pages/intro.html.erb</p>

app/views/pages/signin.html.erb
<!-- TODO fix css -->
<br/><br/><br/><br/><br/><br/><br/><br/><br/>

<div id="user_nav">
	<h1> Sign in with your prefered mehtod</h1>
  <p><%= link_to "Sign in with Developer", "/auth/developer" %></p>
 <p><%= link_to "Sign in with Twitter", "/auth/twitter" %></p>
	<p><%= link_to "Sign in with Facebook", "/auth/facebook" %></p>	
	<p><%= link_to "login", "/auth/identity" %> with a password.</p>

<br/><hr/>
 <%= render 'create' %>	
</div>

app/views/pages/team.html.erb
     <!-- #team -->    
<div class="container-fluid" id="team">
	<div class="container dark">
		<h1>Meet the team</h1>
			<ul class="thumbnails">
			  <li class="span3">
			    <div class="thumbnail">
			      <img alt="" src="assets/img/1.png">
			      <h3>Wang Yahui</h3>
			      <p>Miao.</p>
			      <div class="social">
				      <img alt="" src="assets/img/linkedin.png">
				      <img alt="" src="assets/img/twitter.png">
				      <img alt="" src="assets/img/facebook.png">
				      <img alt="" src="assets/img/email.png">
			      </div>
			    </div>
			  </li>
			
			  <li class="span3">
			    <div class="thumbnail">
			      <img alt="" src="assets/img/1.png">
			      <h3>Mark</h3>
			      <p>Miao.</p>
			      <div class="social">
				      <img alt="" src="assets/img/linkedin.png">
				      <img alt="" src="assets/img/twitter.png">
				      <img alt="" src="assets/img/facebook.png">
				      <img alt="" src="assets/img/email.png">
			      </div>
			    </div>
			  </li>
			  
			  <li class="span3">
			    <div class="thumbnail">
			      <img alt="" src="assets/img/1.png">
			      <h3>Mark</h3>
			      <p>Miao.</p>
			      <div class="social">
				      <img alt="" src="assets/img/linkedin.png">
				      <img alt="" src="assets/img/twitter.png">
				      <img alt="" src="assets/img/facebook.png">
				      <img alt="" src="assets/img/email.png">
			      </div>
			    </div>
			  </li>
			
			  <li class="span3">
			    <div class="thumbnail">
			      <img alt="" src="assets/img/1.png">
			      <h3>Mark</h3>
			      <p>Miao.</p>
			      <div class="social">
				      <img alt="" src="assets/img/linkedin.png"/>
				      <img alt="" src="assets/img/twitter.png"/>
				      <img alt="" src="assets/img/facebook.png"/>
				      <img alt="" src="assets/img/email.png"/>
			      </div>
			    </div>
			  </li>
			 </ul>
		</div>
	</div>
<!-- End Team -->  